"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv
import logging
load_dotenv()  # Load environment variables from .env file

# -------------------------------------------------------
# SENTRY — initialise as early as possible, before apps
# -------------------------------------------------------
import sentry_sdk
_SENTRY_DSN = os.getenv("SENTRY_DSN", "")
if _SENTRY_DSN:
    sentry_sdk.init(
        dsn=_SENTRY_DSN,
        traces_sample_rate=float(os.getenv("SENTRY_TRACES_SAMPLE_RATE", "0.1")),
        send_default_pii=False,
    )


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    from django.core.exceptions import ImproperlyConfigured
    raise ImproperlyConfigured(
        "SECRET_KEY environment variable is not set. "
        "Generate one with: python -c \"from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())\""
    )
BASE_URL = os.getenv('BASE_URL', 'http://localhost:8000')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

# Parse comma-separated hosts, fallback to localhost for dev
env_hosts = os.getenv('ALLOWED_HOSTS', '')
if env_hosts:
    ALLOWED_HOSTS = [host.strip() for host in env_hosts.split(',') if host.strip()]
else:
    from django.core.exceptions import ImproperlyConfigured
    if not DEBUG:
        raise ImproperlyConfigured("ALLOWED_HOSTS must be set in production via environment variable.")
    ALLOWED_HOSTS = ['localhost', '127.0.0.1']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    # Third-party
    'axes',
    # Internal apps
    'accounts',
    'menu',
    'orders',
    'reports',
    'tenants',
    'inventory',
    'notifications',
    'setup',
    'shifts',
    'crm',
    'agency',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # Subdomain → tenant resolution (reads request.get_host())
    'core.middleware.TenantMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # django-axes must come after AuthenticationMiddleware
    'axes.middleware.AxesMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.ContextLoggingMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
		'core.context_processors.base_url',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }




DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.sqlite3'),
        'NAME': os.getenv('DB_NAME', BASE_DIR / 'db.sqlite3'),
        'USER': os.getenv('DB_USER', ''),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', ''),
        'PORT': os.getenv('DB_PORT', ''),
        'CONN_MAX_AGE': int(os.getenv('DB_CONN_MAX_AGE', '60')),
    }
}



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# -------------------------------------------------------
# MEDIA STORAGE — S3 via django-storages
# Set AWS_STORAGE_BUCKET_NAME in env to enable S3 storage.
# Falls back to local disk for development.
# -------------------------------------------------------
_AWS_BUCKET = os.getenv("AWS_STORAGE_BUCKET_NAME", "")
if _AWS_BUCKET:
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }
    AWS_STORAGE_BUCKET_NAME = _AWS_BUCKET
    AWS_S3_REGION_NAME = os.getenv("AWS_S3_REGION_NAME", "ap-south-2")
    AWS_S3_FILE_OVERWRITE = False
    AWS_DEFAULT_ACL = None  # Use bucket policy
    AWS_S3_CUSTOM_DOMAIN = os.getenv("AWS_S3_CUSTOM_DOMAIN", "")
    MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/" if AWS_S3_CUSTOM_DOMAIN else f"https://{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com/"
else:
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }

# Security Headers
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    CSRF_TRUSTED_ORIGINS = os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',')
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = "DENY"

# Default primary key field type

AUTH_USER_MODEL = 'accounts.User'

# -------------------------------------------------------
# AUTHENTICATION BACKENDS — axes must be last
# -------------------------------------------------------
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'axes.backends.AxesStandaloneBackend',
]

# -------------------------------------------------------
# DJANGO-AXES — brute-force login protection
# -------------------------------------------------------
AXES_FAILURE_LIMIT = int(os.getenv("AXES_FAILURE_LIMIT", "5"))  # lockout after 5 failures
AXES_COOLOFF_TIME = 1  # hours before account is unlocked automatically
AXES_LOCKOUT_CALLABLE = None  # use default 403 response
AXES_RESET_ON_SUCCESS = True  # clear failure count on successful login
AXES_USERNAME_FORM_FIELD = "username"
AXES_ENABLE_ADMIN = False  # don't lock admin separately


LOGGING = {

    "version": 1,
    "disable_existing_loggers": False,

    "filters": {
        "tenant_outlet_filter": {
            "()": "core.log_filters.TenantOutletFilter",
        }
    },

    "formatters": {

        "pos_format": {
            "format": "[{levelname}] {asctime} [T:{tenant_id}|O:{outlet_id}] {name} {message}",
            "style": "{",
        }

    },

    "handlers": {

        "file": {
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(BASE_DIR, "pos.log"),
            "maxBytes": 5 * 1024 * 1024,
            "backupCount": 7,
            "formatter": "pos_format",
            "filters": ["tenant_outlet_filter"],
        },

        "console": {

            "class": "logging.StreamHandler",
            "formatter": "pos_format",
            "filters": ["tenant_outlet_filter"],

        },

    },

    "loggers": {
        "pos.notifications": {
            "handlers": ["file", "console"],
            "level": "INFO",
            "propagate": False,
        },
        "pos.menu": {
            "handlers": ["file", "console"],
            "level": "INFO",
            "propagate": False,
        },
        "pos.orders": {
            "handlers": ["file", "console"],
            "level": "INFO",
            "propagate": False,
        },
        "pos.inventory": {
            "handlers": ["file", "console"],
            "level": "INFO",
            "propagate": False,
        },
        "pos.reports": {
            "handlers": ["file", "console"],
            "level": "INFO",
            "propagate": False,
        },
    },

}

# Aggregator webhook IP allowlist
AGGREGATOR_IP_ALLOWLIST = os.getenv(
    'AGGREGATOR_IP_ALLOWLIST', '127.0.0.1'
).split(',')

# Session expires after one full shift (8 hours)
SESSION_COOKIE_AGE = 28800  # 8 hours in seconds
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # also logout when browser closes
