"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv
import logging
load_dotenv()  # Load environment variables from .env file

# -------------------------------------------------------
# SENTRY — initialise as early as possible, before apps
# -------------------------------------------------------
import sentry_sdk
_SENTRY_DSN = os.getenv("SENTRY_DSN", "")
if _SENTRY_DSN:
    sentry_sdk.init(
        dsn=_SENTRY_DSN,
        traces_sample_rate=float(os.getenv("SENTRY_TRACES_SAMPLE_RATE", "0.1")),
        send_default_pii=False,
    )


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    from django.core.exceptions import ImproperlyConfigured
    raise ImproperlyConfigured(
        "SECRET_KEY environment variable is not set. "
        "Generate one with: python -c \"from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())\""
    )
BASE_URL = os.getenv('BASE_URL', 'http://localhost:8000')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

# Parse comma-separated hosts, fallback to localhost for dev
env_hosts = os.getenv('ALLOWED_HOSTS', '')
if env_hosts:
    ALLOWED_HOSTS = [host.strip() for host in env_hosts.split(',') if host.strip()]
else:
    from django.core.exceptions import ImproperlyConfigured
    if not DEBUG:
        raise ImproperlyConfigured("ALLOWED_HOSTS must be set in production via environment variable.")
    ALLOWED_HOSTS = ['localhost', '127.0.0.1']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    # Third-party
    'axes',
    # Internal apps
    'accounts',
    'menu',
    'orders',
    'reports',
    'tenants',
    'inventory',
    'notifications',
    'setup',
    'shifts',
    'crm',
    'agency',
    'django_celery_results',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # Subdomain → tenant resolution (reads request.get_host())
    'core.middleware.TenantMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # django-axes must come after AuthenticationMiddleware
    'axes.middleware.AxesMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.ContextLoggingMiddleware',
    'core.middleware.RequestLoggingMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
		'core.context_processors.base_url',
                'core.context_processors.tenant_features',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }




DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.sqlite3'),
        'NAME': os.getenv('DB_NAME', BASE_DIR / 'db.sqlite3'),
        'USER': os.getenv('DB_USER', ''),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', ''),
        'PORT': os.getenv('DB_PORT', ''),
        'CONN_MAX_AGE': int(os.getenv('DB_CONN_MAX_AGE', '60')),
    }
}



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# -------------------------------------------------------
# MEDIA STORAGE — S3 via django-storages
# Set AWS_STORAGE_BUCKET_NAME in env to enable S3 storage.
# Falls back to local disk for development.
# -------------------------------------------------------
_AWS_BUCKET = os.getenv("AWS_STORAGE_BUCKET_NAME", "")
if _AWS_BUCKET:
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }
    AWS_STORAGE_BUCKET_NAME = _AWS_BUCKET
    AWS_S3_REGION_NAME = os.getenv("AWS_S3_REGION_NAME", "ap-south-2")
    AWS_S3_FILE_OVERWRITE = False
    AWS_DEFAULT_ACL = None  # Use bucket policy
    AWS_S3_CUSTOM_DOMAIN = os.getenv("AWS_S3_CUSTOM_DOMAIN", "")
    MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/" if AWS_S3_CUSTOM_DOMAIN else f"https://{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com/"
else:
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }

# Security Headers
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # Filter out empty strings — if CSRF_TRUSTED_ORIGINS is not set, split(',')
    # produces [''] which silently disables CSRF origin checking entirely.
    _raw_csrf_origins = os.environ.get('CSRF_TRUSTED_ORIGINS', '')
    CSRF_TRUSTED_ORIGINS = [o.strip() for o in _raw_csrf_origins.split(',') if o.strip()]

    # Tell Django the real scheme when running behind nginx or any reverse proxy.
    # Without this, Django sees all requests as HTTP and HTTPS-detection breaks.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True          # allow HSTS preload list submission
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = "DENY"

# Default primary key field type

AUTH_USER_MODEL = 'accounts.User'

# -------------------------------------------------------
# AUTHENTICATION BACKENDS — axes must be last
# -------------------------------------------------------
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'axes.backends.AxesStandaloneBackend',
]

# -------------------------------------------------------
# DJANGO-AXES — brute-force login protection
# -------------------------------------------------------
AXES_FAILURE_LIMIT = int(os.getenv("AXES_FAILURE_LIMIT", "5"))  # lockout after 5 failures
AXES_COOLOFF_TIME = 1  # hours before account is unlocked automatically
AXES_LOCKOUT_CALLABLE = None  # use default 403 response
AXES_RESET_ON_SUCCESS = True  # clear failure count on successful login
AXES_USERNAME_FORM_FIELD = "username"
AXES_ENABLE_ADMIN = False  # don't lock admin separately


_LOG_DIR = BASE_DIR / "logs"
_LOG_DIR.mkdir(exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,

    "filters": {
        "tenant_outlet": {
            "()": "core.log_filters.TenantOutletFilter",
        },
        "require_debug_false": {
            "()": "django.utils.log.RequireDebugFalse",
        },
    },

    "formatters": {
        # Short format for console during development
        "simple": {
            "format": "[{levelname}] {name}: {message}",
            "style": "{",
        },
        # Full format for all file handlers
        "verbose": {
            "format": (
                "[{levelname}] {asctime} pid={process:d} "
                "[T:{tenant_id}|O:{outlet_id}] {name} {message}"
            ),
            "style": "{",
        },
        # Request-specific format (no tenant filter — uses its own fields)
        "request_fmt": {
            "format": (
                "[{levelname}] {asctime} {message}"
            ),
            "style": "{",
        },
    },

    "handlers": {
        # ── Console ──────────────────────────────────────────────
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
            "filters": ["tenant_outlet"],
            "level": "DEBUG",
        },

        # ── Main application log (all POS events) ────────────────
        "pos_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": str(_LOG_DIR / "pos.log"),
            "maxBytes": 10 * 1024 * 1024,   # 10 MB
            "backupCount": 10,
            "formatter": "verbose",
            "filters": ["tenant_outlet"],
            "level": "DEBUG",
            "encoding": "utf-8",
        },

        # ── Errors only (WARNING+) ───────────────────────────────
        "error_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": str(_LOG_DIR / "errors.log"),
            "maxBytes": 5 * 1024 * 1024,    # 5 MB
            "backupCount": 10,
            "formatter": "verbose",
            "filters": ["tenant_outlet"],
            "level": "WARNING",
            "encoding": "utf-8",
        },

        # ── Django framework / request log ───────────────────────
        "django_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": str(_LOG_DIR / "django.log"),
            "maxBytes": 10 * 1024 * 1024,
            "backupCount": 7,
            "formatter": "request_fmt",
            "level": "INFO",
            "encoding": "utf-8",
        },

        # ── Security events (login failures, CSRF, etc.) ─────────
        "security_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": str(_LOG_DIR / "security.log"),
            "maxBytes": 5 * 1024 * 1024,
            "backupCount": 10,
            "formatter": "request_fmt",
            "level": "DEBUG",
            "encoding": "utf-8",
        },
    },

    "loggers": {
        # ── Django internal loggers ───────────────────────────────
        "django": {
            "handlers": ["django_file", "console"],
            "level": "INFO",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["django_file", "error_file"],
            "level": "WARNING",   # logs 4xx/5xx with full tracebacks
            "propagate": False,
        },
        "django.security": {
            "handlers": ["security_file", "error_file"],
            "level": "DEBUG",
            "propagate": False,
        },
        "django.db.backends": {
            # Set to DEBUG to log every SQL query; INFO to suppress
            "handlers": ["pos_file"],
            "level": "INFO",
            "propagate": False,
        },

        # ── POS application loggers ───────────────────────────────
        "pos": {
            # Root POS logger — all pos.* namespaces inherit this
            "handlers": ["pos_file", "error_file", "console"],
            "level": "DEBUG",
            "propagate": False,
        },
        "pos.notifications": {
            "handlers": ["pos_file", "error_file", "console"],
            "level": "DEBUG",
            "propagate": False,
        },
        "pos.menu": {
            "handlers": ["pos_file", "error_file", "console"],
            "level": "DEBUG",
            "propagate": False,
        },
        "pos.orders": {
            "handlers": ["pos_file", "error_file", "console"],
            "level": "DEBUG",
            "propagate": False,
        },
        "pos.inventory": {
            "handlers": ["pos_file", "error_file", "console"],
            "level": "DEBUG",
            "propagate": False,
        },
        "pos.reports": {
            "handlers": ["pos_file", "error_file", "console"],
            "level": "DEBUG",
            "propagate": False,
        },
        "pos.billing": {
            "handlers": ["pos_file", "error_file", "console"],
            "level": "DEBUG",
            "propagate": False,
        },
        "pos.auth": {
            "handlers": ["security_file", "pos_file", "error_file", "console"],
            "level": "DEBUG",
            "propagate": False,
        },
        "pos.setup": {
            "handlers": ["pos_file", "error_file", "console"],
            "level": "DEBUG",
            "propagate": False,
        },
        "pos.core": {
            "handlers": ["pos_file", "error_file", "console"],
            "level": "DEBUG",
            "propagate": False,
        },
        "pos.shifts": {
            "handlers": ["pos_file", "error_file", "console"],
            "level": "DEBUG",
            "propagate": False,
        },
        "pos.crm": {
            "handlers": ["pos_file", "error_file", "console"],
            "level": "DEBUG",
            "propagate": False,
        },
    },
}

# Aggregator webhook IP allowlist
AGGREGATOR_IP_ALLOWLIST = os.getenv(
    'AGGREGATOR_IP_ALLOWLIST', '127.0.0.1'
).split(',')

# -------------------------------------------------------
# AUTH REDIRECT
# Django's @login_required defaults to /accounts/login/ which 404s.
# Set LOGIN_URL to the actual login view.
# -------------------------------------------------------
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'

# -------------------------------------------------------
# WHATSAPP RECEIPTS
# Backend 1 (preferred): Meta WhatsApp Business Cloud API — free 1000 msg/month
#   META_WHATSAPP_TOKEN    = your permanent system user token
#   META_WHATSAPP_PHONE_ID = phone number ID from Meta Business dashboard
# Backend 2 (fallback): Twilio
#   TWILIO_ACCOUNT_SID, TWILIO_AUTH_TOKEN, TWILIO_WHATSAPP_FROM
# Leave all blank to disable silently.
# -------------------------------------------------------
META_WHATSAPP_TOKEN   = os.getenv("META_WHATSAPP_TOKEN", "")
META_WHATSAPP_PHONE_ID = os.getenv("META_WHATSAPP_PHONE_ID", "")

TWILIO_ACCOUNT_SID   = os.getenv("TWILIO_ACCOUNT_SID", "")
TWILIO_AUTH_TOKEN    = os.getenv("TWILIO_AUTH_TOKEN", "")
TWILIO_WHATSAPP_FROM = os.getenv("TWILIO_WHATSAPP_FROM", "whatsapp:+14155238886")

# -------------------------------------------------------
# SESSION — long enough for a full 12-hour QSR shift.
# SESSION_EXPIRE_AT_BROWSER_CLOSE removed:
#   Tablets used as POS terminals rarely close the browser tab.
#   With it set to True, sessions expired silently when the browser
#   process briefly restarted (e.g. tablet sleep → wake). Staff would
#   hit /token/X/bill/ and see "Order not found" because @login_required
#   was redirecting to /accounts/login/ (404) instead of /login/.
# -------------------------------------------------------
SESSION_COOKIE_AGE = 43200  # 12 hours in seconds
SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'

# -------------------------------------------------------
# CACHE — Redis backend so sessions are shared across all
# Gunicorn workers. Without this, SESSION_ENGINE=cached_db
# falls back to LocMemCache (in-process) and sessions are
# NOT shared between workers → random logouts every 2-3
# requests. This is a production-breaking bug without Redis.
# -------------------------------------------------------
REDIS_URL = os.getenv("REDIS_URL", "redis://127.0.0.1:6379/0")

import sys as _sys
_TESTING = len(_sys.argv) > 1 and _sys.argv[1] == "test"

CACHES = {
    "default": {
        "BACKEND": (
            # Tests run without Redis — use in-process cache.
            # Production must have Redis so sessions are shared across workers.
            "django.core.cache.backends.locmem.LocMemCache"
            if _TESTING else
            "django.core.cache.backends.redis.RedisCache"
        ),
        "LOCATION": "" if _TESTING else REDIS_URL,
        "TIMEOUT": 300,
    }
}

CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = "django-db"
CELERY_CACHE_BACKEND = "django-cache"
CELERY_RESULT_EXTENDED = True

CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "Asia/Kolkata"

# If Redis is unreachable, fall back gracefully instead of crashing the request.
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_BROKER_CONNECTION_RETRY = True
CELERY_BROKER_CONNECTION_MAX_RETRIES = 3

# Printing tasks should be fast; kill them if they run over 60 seconds.
CELERY_TASK_SOFT_TIME_LIMIT = 30   # raises SoftTimeLimitExceeded
CELERY_TASK_TIME_LIMIT      = 60   # hard kill after 60s

# Two queues: default for everything, printing for thermal printer tasks.
# This lets you prioritise print jobs without blocking other tasks.
CELERY_TASK_ROUTES = {
    "orders.tasks.print_kot_task":  {"queue": "printing"},
    "orders.tasks.print_bill_task": {"queue": "printing"},
}

CELERY_TASK_DEFAULT_QUEUE = "default"

# Acknowledge tasks AFTER completion, not on receipt.
# If the worker crashes mid-task, the task is re-queued for the next worker.
# Combined with idempotency keys in tasks.py this prevents both lost tasks
# and double-printing.
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_REJECT_ON_WORKER_LOST = True

# Discard tasks queued more than 30 minutes ago — stale print jobs from a
# previous session should not print when the worker restarts.
CELERY_TASK_EXPIRES = 1800  # seconds
